spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Vroom
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
